apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-bridge-dualstack
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "ens3",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "ranges": [
          [
            {
              "subnet": "192.168.22.0/24",
              "rangeStart": "192.168.22.100",
              "rangeEnd": "192.168.22.200"
            }
          ],
          [
            {
              "subnet": "fd00::192:168:22:0/112",
              "rangeStart": "fd00::192:168:22:100",
              "rangeEnd": "fd00::192:168:22:200"
            }
          ]
        ]    
      }
    }'
