apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata: 
  name: macvlan-bridge-whereabouts
spec: 
  config: '{
      "cniVersion": "0.3.1",
      "name": "whereabouts",
      "type": "macvlan",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.199.199.0/24",
        "range_start": "10.199.199.100",
        "gateway": "10.199.199.1"
      }
}'
