apiVersion: v1
kind: Pod
metadata:
  name: egress-http-proxy
  labels:
    name: egress-http-proxy
  annotations:
    pod.network.openshift.io/assign-macvlan: "true"
spec:
  initContainers:
  - name: egress-router-setup
    image: openshift3/ose-egress-router
    securityContext:
      privileged: true
    env:
    - name: EGRESS_SOURCE
      value: 192.168.12.99
    - name: EGRESS_GATEWAY
      value: 192.168.12.1
    - name: EGRESS_ROUTER_MODE
      value: http-proxy
  containers:
  - name: egress-router-proxy
    imagePullPolicy: IfNotPresent
    image: openshift3/ose-egress-http-proxy
    env:
    - name: EGRESS_HTTP_PROXY_DESTINATION
      value: |
        !*.redhat.com
        !98.0.0.0/8
        !69.172.200.235/32
        !www.cisco.com
        *
