apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: allow-podselector-and-namespaceselector
  annotations:
    k8s.v1.cni.cncf.io/policy-for: macvlan-net1
spec:
  podSelector: 
    matchLabels:
      name: red-openshift
  ingress:
    - from:
      - namespaceSelector:     
          matchLabels:
            user: alice
        podSelector:
          matchLabels:
            name: red-openshift  
