#oc new-project test1
#oc adm policy add-scc-to-user -z default hostnetwork -n test1
#oc create -f https://raw.githubusercontent.com/weliang1/Openshift_Networking/master/Features/Pod/debug-network-pod1.yaml

apiVersion: v1
kind: Pod
metadata:
  name: debug-network-pod1
spec:
  containers:
  - name: debug-network-pod1
    image: docker.io/bmeng/centos-network
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  hostNetwork: true
