---
kind: Pod
apiVersion: v1
metadata:
  name: blue-pod-1
  labels:
    name: blue-openshift
spec:
  containers:
  - name: blue-pod-container
    image: quay.io/openshifttest/newone
    env:
    - name: RESPONSE
      value: Hello Blue Pod-1 Example
    ports:
    - containerPort: 8080
    - containerPort: 443
