apiVersion: v1
kind: Pod
metadata:
  name: multihoming-red
  annotations:
    k8s.v1.cni.cncf.io/networks: testmacvlan, testmacvlan1
spec:
  containers:
  - name: multihoming-red
    ports:
        - containerPort: 30102
          protocol: SCTP
    image: quay.io/openshifttest/centos-network@sha256:48da37205f9b43424e0983d4c5e7e07f77b7ba1504bbe35e2f264c75dcb4cd15
  nodeSelector: 
    name: red
