apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipam-name
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ipam-type",
      "master": "ens3",
      "ipam": {
        "type": "host-local",
        "subnet": "fd00::22:2:2:0/112",
        "rangeStart": "fd00::22:2:2:100",
        "rangeEnd": "fd00::22:2:2:200"
      }
    }'
