apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-host-local
spec:
  config: '{
        "cniVersion": "0.3.1",
	      "name": "ipvlan-host-local",
	      "master": "eth0",
	      "type": "ipvlan",
	      "ipam": {
		             "type": "host-local",
		             "subnet": "22.2.2.0/24"
	}
}'
