apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata: 
  name: macvlan-bridge-whereabouts
spec: 
  config: '{
      "cniVersion": "0.3.0",
      "name": "whereabouts",
      "type": "macvlan",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.22.100/30"
      }
}'
