kind: Pod
apiVersion: v1
metadata:
  name: blue-pod-4
  labels:
    name: blue-openshift
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-net1
spec:
  containers:
  - name: blue-pod-container
    image: bmeng/hello-openshift
    env:
    - name: RESPONSE
      value: Hello Blue Pod-4 Example
    ports:
    - containerPort: 8080
    - containerPort: 443
