apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name:  egress-allow-diff-podselector-with-same-namespaceselector
  annotations:
    k8s.v1.cni.cncf.io/policy-for: macvlan-net1
spec:
  podSelector: 
    matchLabels:
      name: blue-openshift
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:     
        matchLabels:
          user: projecta
      podSelector:
        matchLabels:
          name: red-openshift 
