kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name:  Ingress-allow-same-podSelector-with-same-namespaceSelector
spec:
  podSelector: 
    matchLabels:
      name: blue-openshift
  ingress:
    - from:
      - namespaceSelector:     
          matchLabels:
            user: projecta
        podSelector:
          matchLabels:
            name: blue-openshift 
