apiVersion: networking.k8s.io/v1
kind: MultiNetworkPolicy
metadata:
  name:  ingress-allow-same-podselector-with-same-namespaceselector
  annotations:
    k8s.v1.cni.cncf.io/policy-for: macvlan-net1
spec:
  podSelector: 
    matchLabels:
      name: blue-openshift
  ingress:
    - from:
      - namespaceSelector:     
          matchLabels:
            user: projecta
        podSelector:
          matchLabels:
            name: blue-openshift 
