apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-net2
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "mode": "bridge",
      "master": "eno2",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.22.60-192.168.22.100/24"
      }
    }'
