apiVersion: v1
kind: Pod
metadata:
  name: egressrouter-redirect-pod
  labels:
    name: egressrouter-redirect-pod
  annotations:
    pod.network.openshift.io/assign-macvlan: "true"
spec:
  initContainers:
  - name: egressrouter-redirectpod
    image: registry.redhat.io/openshift4/ose-egress-router 
    imagePullPolicy:  IfNotPresent
    securityContext:
      privileged: true
    env:
    - name: EGRESS_SOURCE
      value: 172.31.249.212
    - name: EGRESS_GATEWAY
      value: 172.31.248.1
    - name: EGRESS_DESTINATION 
      value:  216.58.217.46
    - name: EGRESS_ROUTER_MODE
      value: init
  containers:
  - name: registry.redhat.io/openshift4/ose-pod
    image: openshift3/ose-pod
    imagePullPolicy:  IfNotPresent
  nodeSelector:
    app:  egressrouter
