apiVersion: network.operator.openshift.io/v1
kind: EgressRouter
metadata:
  name: egress-router-test
  namespaces: test
spec:
  addresses: [
    {
      ip: "10.73.116.60/23",
      gateway: "10.73.117.254",
    },
  ]
  mode: Redirect
  redirect: {
    redirectRules: [
      {
        destinationIP: "142.250.81.206",
        port: 80,
        protocol: TCP,
      },
      {
        destinationIP: "23.218.161.207",
        port: 8080,
        protocol: TCP,
        targetPort: 80
      },
      {
        destinationIP: "209.82.215.211",
        port: 8888,
        protocol: TCP,
        targetPort: 80
      },
    ]
  }
