apiVersion: "k8s.cni.cncf.io/v1" 
kind: NetworkAttachmentDefinition 
metadata: 
  name: ovn-egressrouter-redirect 
spec: 
  config: '{ 
    "cniVersion": "0.4.0", 
    "type": "egress-router", 
    "name": "ovn-egressrouter-redirect", 
    "ip": { 
      "addresses": [ 
        "10.0.193.103/8" 
        ], 
      "destinations": [ 
        "142.250.81.206" 
      ], 
      "gateway": "10.0.192.1" 
      },
      "log_file": "/tmp/egress-router-log", 
      "log_level": "debug"  
  }'
