apiVersion: network.operator.openshift.io/v1
kind: EgressRouter
metadata:
  name: egress-router-5
spec:
  addresses: [
    {
      ip: "192.168.3.10/24",
      gateway: "192.168.3.1",
    },
  ]
  mode: Redirect
  redirect: {
    redirectRules: [
      {
        destinationIP: "203.0.113.25/30",
        port: 65,
        protocol: TCP,
        targetPort: 75
      },
      {
        destinationIP: "203.0.113.26/30",
        port: 65535,
        protocol: SCTP,
      },
      {
        destinationIP: "203.0.113.27/30",
        port: 65534,
        protocol: UDP,
      },
    ],
    fallbackIP: "203.0.113.28/30"
  }
