apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostnetwork-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hostnetwork-pod
  template:
    metadata:
      labels:
        name: hostnetwork-pod
    spec:
      containers:
      - name: hostnetwork-pod
        image: quay.io/openshifttest/centos-network@sha256:48da37205f9b43424e0983d4c5e7e07f77b7ba1504bbe35e2f264c75dcb4cd15
        ports:
        - containerPort: 8080
        - containerPort: 443
        env:
        - name: RESPONSE
          value: hostnetwork-pod
      securityContext:
        privileged: true
      capabilities:
        add: ["NET_ADMIN"]
    hostNetwork: true
