apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-bridge
spec:
  config: '{
      "cniVersion": "0.3.1",
      "bridge": "my-bridge",
      "type": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "22.2.2.0/24",
        "rangeStart": "22.2.2.100",
        "rangeEnd": "22.2.2.200"
      }
    }'
